Welcome to the Open Motif ftp server.

All activity is logged with your host name and email address.

REPORTING PROBLEMS - Please report all problems to 
	openmotif-admin@opengroup.org.

LOGIN PROBLEMS - If your FTP client crashes or hangs shortly after 
login, try using a dash (-) as the first character of your password.  
This turns off the informational messages that may be confusing 
your ftp client.

COMPRESSED FILES - To compress or tar a file or directory on the 
fly, use "get [directory].[suffix]" or "get [file].[suffix]" where 
[suffix] is gz, Z, tar, tar.Z, or tar.gz. To uncompress a compressed 
file or directory before downloading, strip suffixes from filenames.

** CALL FOR CONTRIBUTIONS **

If you have developed Open Motif applications that you would like 
to share please upload them to the 
	ftp://openmotif.opengroup.org/pub/openmotif/contrib/INCOMING  
directory.  We appreciate your contribution

For more information on Open Motif, including information on mailing
lists and  frequently asked questions 
see URL: http://www.opengroup.org/openmotif/
